### PR TITLE
Fix duplicate symbols for downstream CAPIObjects users

### PR DESCRIPTION
**Pull request by cerisier**
Should fix failure in https://github.com/openxla/xla/pull/22438

I need just a bit more time to validate this entirely on Linux

### CODE REVIEW

**Review by GleasonK — APPROVED** [review]

**Comment by GleasonK** [comment]
Patched your change and validated using XLA CI, going to merge this to keep things in sync
